teams/account/urls.py
from django.urls import path, include


from account.views import (
    UserLoginView,
    UserLogoutView,
    register,
    edit,
    dashboard,
    user_detail,
)


urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("register/", register, name="register"),
    path("edit/", edit, name="edit"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("", dashboard, name="dashboard"),
    path("users/<username>/", user_detail, name="user_detail"),
]

teams/games/urls.py
from django.urls import path

from games.views import game_create, game_detail, game_list, game_join, get_player_list

app_name = "games"

urlpatterns = [
    path("create/", game_create, name="create"),
    path("detail/<int:id>/<slug:slug>/", game_detail, name="detail"),
    path('join/', game_join, name='join'),
    path('get_player_list/<int:game_id>/', get_player_list, name='get_player_list'),
    path('', game_list, name='list'),
]

teams/teams/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("account.urls")),
    path("games/", include("games.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

teams/account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    location = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse("user_detail", args=[str(self.id)])

teams/account/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django.forms import TextInput, DateInput, EmailInput

from account.models import Profile


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = AuthenticationForm
        fields = ["username", "password"]


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={"class": "form-control"}))
    username = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control"})
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control"})
    )

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Email already in use.")
        return email


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "email"]
        widgets = {
            "first_name": TextInput(
                attrs={
                    "class": "form-control mr-2",
                    "placeholder": "Имя пользователя",
                }
            ),
            "last_name": TextInput(
                attrs={
                    "class": "form-control mr-2",
                    "placeholder": "Фамилия пользователя",
                }
            ),
            "email": EmailInput(
                attrs={
                    "class": "form-control mr-2",
                    "placeholder": "Электронная почта",
                }
            ),
        }

    def clean_email(self):
        data = self.cleaned_data["email"]
        qs = User.objects.exclude(id=self.instance.id).filter(email=data)
        if qs.exists():
            raise forms.ValidationError("Email already in use.")
        return data


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["date_of_birth", "location"]
        widgets = {
            "date_of_birth": DateInput(
                attrs={
                    "class": "form-control mr-2",
                    "type": "date",
                    "placeholder": "Enter your birth date",
                    "name": "date_of_birth",
                    "id": "id_date_of_birth",
                }
            ),
            "location": TextInput(
                attrs={
                    "class": "form-control mr-2",
                    "placeholder": "Введите название города",
                    "name": "location",
                    "id": "id_location",
                    "autocomplete": "off",
                }
            ),
        }

teams/account/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy

from account.forms import UserLoginForm, UserRegisterForm, UserEditForm, ProfileEditForm
from account.models import Profile


class UserLoginView(LoginView):
    form_class = UserLoginForm
    template_name = "account/login.html"
    success_url = reverse_lazy("dashboard")
    redirect_authenticated_user = True


class UserLogoutView(LogoutView):
    next_page = "login"


@login_required
def dashboard(request):
    return render(
        request,
        "account/dashboard.html",
        {
            "section": "dashboard",
        },
    )


def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data["password1"])
            new_user.save()
            Profile.objects.create(user=new_user)
            login(request, new_user)
            return redirect("dashboard")
        else:
            print(form.errors)
    else:
        form = UserRegisterForm()
    return render(request, "registration/register.html", {"form": form})


@login_required
def edit(request):
    user = request.user
    profile = user.profile

    if request.method == "POST":
        user_form = UserEditForm(instance=user, data=request.POST)
        profile_form = ProfileEditForm(
            instance=profile, data=request.POST, files=request.FILES
        )

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, "Profile updated successfully")
            return redirect("dashboard")
        else:
            messages.error(request, "Error updating your profile")
    else:
        user_form = UserEditForm(instance=user)
        profile_form = ProfileEditForm(instance=profile)

    return render(
        request,
        "account/edit.html",
        {"user_form": user_form, "profile_form": profile_form},
    )


@login_required
def user_detail(request, username):
    user = get_object_or_404(User, username=username, is_active=True)
    return render(request, "user/detail.html", {"section": "people", "user": user})

teams/account/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}Главная страница{% endblock %}</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" rel="stylesheet">
</head>
<body>
  {% if request.user.is_authenticated %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <ul class="navbar-nav">
                <li class="nav-item {% if section == 'main' %}active{% endif %}">
                    <a class="nav-link" href="/">Главная</a>
                </li>
                <li class="nav-item {% if section == 'games' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'games:list' %}">Игры</a>
                </li>
                <li class="nav-item {% if section == 'locations' %}active{% endif %}">
                    <a class="nav-link" href="locations">Локации</a>
                </li>
            </ul>
            <div class="ml-auto">
                {% if request.user.is_authenticated %}
                        <form action="{% url 'logout' %}" method="post" class="d-inline">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-success nav-link">Выйти</button>
                        </form>
                {% else %}
                        <a class="nav-link" href="{% url 'login' %}">Войти</a>
                {% endif %}
            </div>
        </div>
    </nav>
  {% endif %}

  <script src="//cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>
  <!-- Загрузка JavaScript в DOM -->
  <script>
      const csrftoken = Cookies.get('csrftoken');
      document.addEventListener('DOMContentLoaded', (event) => {
          // DOM загружена
          {% block domready %}
          {% endblock %}
      })
  </script>

  <div class="container mt-4">
    {% block content %}
    {% endblock %}
  </div>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
  <script src="http://cdn.jsdelivr.net/npm/suggestions-jquery@22.6.0/dist/js/jquery.suggestions.min.js"></script>
  <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/scripts.js' %}"></script>
  <script src="https://mapgl.2gis.com/api/js/v1"></script>
</body>
</html>