teams/games/urls.py
from django.urls import path

from games.views import game_create, game_detail, game_list, game_join, get_player_list

app_name = "games"

urlpatterns = [
    path("create/", game_create, name="create"),
    path("detail/<int:id>/<slug:slug>/", game_detail, name="detail"),
    path('join/', game_join, name='join'),
    path('get_player_list/<int:game_id>/', get_player_list, name='get_player_list'),
    path('', game_list, name='list'),
]

teams/teams/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("account.urls")),
    path("games/", include("games.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

teams/games/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify


class Game(models.Model):
    SPORTS = (
        ("football", "футбол"),
        ("tennis", "теннис"),
        ("bowling", "боулинг"),
        ("beach volleyball", "пляжный волейбол"),
        ("volleyball", "волейбол"),
        ("ice hockey", "хоккей на льду"),
        ("chess", "шахматы"),
    )
    SPORT_ICONS = {
        "football": "fas fa-futbol",
        "tennis": "fas fa-table-tennis",
        "bowling": "fas fa-bowling-ball",
        "beach volleyball": "fas fa-volleyball-ball",
        "volleyball": "fas fa-volleyball-ball",
        "ice hockey": "fas fa-hockey-puck",
        "chess": "fas fa-chess",
    }

    CHOICES = (("open", "Open"), ("started", "Started"), ("finished", "Finished"))

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="user_games_created",
        on_delete=models.CASCADE,
    )
    sport = models.CharField(max_length=255, choices=SPORTS)
    city = models.CharField(max_length=100, default="Самара")
    place = models.CharField(max_length=255)
    date = models.DateField(default=timezone.now)
    start_time = models.TimeField(default=timezone.now)
    duration = models.DurationField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    max_players = models.PositiveIntegerField(default=2)
    joined_players = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="joined_games", blank=True
    )
    status = models.CharField(max_length=255, choices=CHOICES, default="Open")
    slug = models.SlugField(max_length=200)

    class Meta:
        verbose_name = "Игра"
        verbose_name_plural = "Игры"
        indexes = [
            models.Index(fields=["created_at"]),
        ]
        ordering = ["created_at"]

    def __str__(self):
        return f"{self.sport} {self.date} {self.start_time} {self.place}"

    def save(self, *args, **kwargs):
        """
        Если слаг не задан, генерирует его из названия вида спорта, даты и места.
        """
        if not self.slug:
            self.slug = (
                slugify(self.sport, allow_unicode=True)
                + "-"
                + slugify(self.date, allow_unicode=True)
                + "-"
                + slugify(self.created_at, allow_unicode=True)
                + "-"
                + slugify(self.user, allow_unicode=True)
            )
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("games:detail", args=[self.id, self.slug])

teams/games/forms.py
from django import forms
from django.forms import Select, TextInput, NumberInput, Textarea

from .models import Game


class GameCreateForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = [
            "sport",
            "city",
            "place",
            "date",
            "start_time",
            "duration",
            "max_players",
            "price",
            "description",
        ]
        labels = {
            "sport": "Вид спорта",
            "city": "Город",
            "place": "Место игры",
            "date": "Дата игры",
            "start_time": "Время начала игры",
            "duration": "Продолжительность",
            "max_players": "Количество игроков",
            "price": "Цена игры",
            "description": "Описание",
        }

        widgets = {
            "sport": Select(
                attrs={
                    "class": "form-control form-control-width",
                    "style": "background-color: #f8f9fa; border-radius: 5px;",
                }
            ),
            "city": TextInput(
                attrs={
                    "class": "form-control form-control-width",
                    "style": "background-color: #f8f9fa; border-radius: 5px;",
                    "placeholder": "Введите название города",
                    "name": "location",
                    "id": "id_location",
                    "autocomplete": "off",
                }
            ),
            "place": TextInput(
                attrs={
                    "class": "form-control form-control-width",
                    "style": "background-color: #f8f9fa; border-radius: 5px;",
                    "placeholder": "Введите место игры",
                }
            ),
            "max_players": NumberInput(
                attrs={
                    "class": "form-control form-control-width",
                    "step": "1",
                    "style": "background-color: #f8f9fa; border-radius: 5px;",
                }
            ),
            "description": Textarea(
                attrs={
                    "cols": 30,
                    "rows": 3,
                    "class": "form-control form-control-width",
                    "type": "text",
                    "placeholder": "Опишите например: есть душевые, есть парковочные места",
                    "aria-label": "default input example",
                    "style": "background-color: #f8f9fa; border-radius: 5px;",
                }
            ),
            "price": NumberInput(
                attrs={
                    "step": "10",
                    "class": "form-control form-control-width",
                    "style": "background-color: #f8f9fa; border-radius: 5px;",
                    "placeholder": "Введите цену игры",
                }
            ),
            "duration": TextInput(
                attrs={
                    "placeholder": "HH:MM",
                    "type": "time",
                    "class": "form-control form-control-width",
                    "style": "background-color: #f8f9fa; border-radius: 5px;",
                }
            ),
            "date": TextInput(
                attrs={
                    "placeholder": "HH:MM",
                    "type": "date",
                    "class": "form-control form-control-width",
                    "style": "background-color: #f8f9fa; border-radius: 5px;",
                }
            ),
            "start_time": TextInput(
                attrs={
                    "placeholder": "HH:MM",
                    "type": "time",
                    "class": "form-control form-control-width",
                    "style": "background-color: #f8f9fa; border-radius: 5px;",
                }
            ),
        }

teams/games/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse, HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.template.loader import render_to_string
from django.views.decorators.http import require_POST

from games.forms import GameCreateForm
from games.models import Game


@login_required
def game_create(request):
    if request.method == "POST":
        form = GameCreateForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_game = form.save(commit=False)
            new_game.user = request.user
            new_game.save()
            messages.success(request, "Игра успешно создана")
            return redirect(new_game.get_absolute_url())
    else:
        form = GameCreateForm()
    return render(request, "games/game/create.html", {"section": "games", "form": form})


def game_detail(request, id, slug):
    game = get_object_or_404(Game, id=id, slug=slug)
    return render(
        request,
        "games/game/detail.html",
        {
            "section": "games",
            "game": game,
        },
    )


@login_required
def game_list(request):
    games = Game.objects.all()
    paginator = Paginator(games, 4)
    page = request.GET.get('page')
    games_only = request.GET.get('games_only')
    try:
        games = paginator.page(page)
    except PageNotAnInteger:
        games = paginator.page(1)
    except EmptyPage:
        if games_only:
            return HttpResponse('')
        games = paginator.page(paginator.num_pages)
    if games_only:
        return render(request,
                      'games/game/list_games.html',
                      {"section": 'games',
                       'games': games})
    return render(request,
                  'games/game/list.html',
                  {"section": 'games',
                   'games': games})


@login_required
@require_POST
def game_join(request):
    game_id = request.POST.get('id')
    # action берется из атрибута action="/submit", если его нет, то есть ещё варианты.
    action = request.POST.get('action')
    if game_id and action:
        try:
            game = Game.objects.get(id=game_id)
            if action == 'join':
                if game.joined_players.count() >= game.max_players:
                    messages.error(request,
                                     'Максимальное количество игроков достигнуто.')
                    return JsonResponse({'status': 'error',
                                         'message': 'Максимальное количество игроков достигнуто.'})
                game.joined_players.add(request.user)
            else:
                game.joined_players.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except Game.DoesNotExist:
            pass
    return JsonResponse({'status': 'error'})


@login_required
def get_player_list(request, game_id):
    game = get_object_or_404(Game, id=game_id)
    joined_players = game.joined_players.all()

    # Рендерим HTML для списка игроков
    player_list_html = render_to_string('games/game/player_list.html', {
        'joined_players': joined_players,
    })

    return JsonResponse({
        'status': 'ok',
        'player_list_html': player_list_html,
    })

teams/games/templates/games/game/create.html
{% extends "base.html" %}

{% block title %} Создать игру {% endblock %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center">Создать игру</h2>

    <div class="card">
        <div class="card-body">
            <form method="post" class="mt-4">
                {% csrf_token %}

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="{{ form.sport.id_for_label }}">{{ form.sport.label }}</label>
                        {{ form.sport.errors }}
                        {{ form.sport }}
                    </div>
                    <div class="form-group col-md-6">
                        <label for="{{ form.city.id_for_label }}">{{ form.city.label }}</label>
                        {{ form.city.errors }}
                        {{ form.city }}
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="{{ form.place.id_for_label }}">{{ form.place.label }}</label>
                        {{ form.place.errors }}
                        {{ form.place }}
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="{{ form.date.id_for_label }}">{{ form.date.label }}</label>
                        {{ form.date.errors }}
                        {{ form.date }}
                    </div>
                    <div class="form-group col-md-6">
                        <label for="{{ form.start_time.id_for_label }}">{{ form.start_time.label }}</label>
                        {{ form.start_time.errors }}
                        {{ form.start_time }}
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="{{ form.duration.id_for_label }}">{{ form.duration.label }}</label>
                        {{ form.duration.errors }}
                        {{ form.duration }}
                    </div>
                    <div class="form-group col-md-6">
                        <label for="{{ form.max_players.id_for_label }}">{{ form.max_players.label }}</label>
                        {{ form.max_players.errors }}
                        {{ form.max_players }}
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="{{ form.price.id_for_label }}">{{ form.price.label }}</label>
                        {{ form.price.errors }}
                        {{ form.price }}
                    </div>
                    <div class="form-group col-md-6">
                        <label for="{{ form.description.id_for_label }}">{{ form.description.label }}</label>
                        {{ form.description.errors }}
                        {{ form.description }}
                    </div>
                </div>

                <button type="submit" class="btn btn-primary btn-block mt-3">Создать игру</button>
            </form>
            <div id="validationResult" class="mt-3 text-center"></div>
        </div>
    </div>

    <div class="mt-3 text-center">
        <p>* Поля со звёздочкой являются обязательными</p>
    </div>
</div>
{% endblock %}

teams/games/templates/games/game/detail.html
{% extends "base.html" %}

{% block title %}{{ game.sport }} | {{ user.username }}{% endblock %}

{% block content %}

    <h1>{{ game.get_sport_display }}</h1>
        <p>{{ user.first_name }} - {{ user.email }}</p>
        <p>
            <i class="fas fa-calendar"></i> {{ game.date }}&nbsp;&nbsp;&nbsp;
            <i class="fas fa-clock"></i> {{ game.start_time }}&nbsp;&nbsp;&nbsp;
            <i class="fas fa-map-marker"></i> {{ game.place }}
        </p>
    <p>{{ game.description }}</p>

    <p>
      <i class="fas fa-coins"></i> {{ game.price }}
    </p>

    {% with total_jones=game.joined_players.count joined_players=game.joined_players.all %}
    <div>
        <p><i class="fas fa-users"></i>
        <span class="count">
            {{ total_jones }} / {{ game.max_players }}
        </span>
        </p>
        <a href="#" data-id="{{ game.id }}"
           data-action="{% if request.user in joined_players %}un{% endif %}join"
           data-max-players="{{ game.max_players }}"
           class="like button">
            {% if request.user not in joined_players %}
                Join
            {% else %}
                Unjoin
            {% endif %}
        </a>
    </div>
        <div class="image-likes" id="player-list">
            {% for user in joined_players %}
                <div>
                    <p>{{ user.username }}</p>
                </div>
            {% empty %}
                Nobody players joined
            {% endfor %}
        </div>
    {% endwith %}
{% endblock %}

{% block domready %}
    const url = '{% url "games:join" %}';

    var options = {
        method: 'POST',
        headers: {'X-CSRFToken': csrftoken},
        mode: 'same-origin'
    }

    document.querySelector('a.button')
            .addEventListener('click', function(e){
        e.preventDefault();
        var joinButton = this;

        var gameId = joinButton.dataset.id;
        var action = joinButton.dataset.action;

    // добавить тело запроса
        var formData = new FormData();
        formData.append('id', joinButton.dataset.id);
        formData.append('action', joinButton.dataset.action);
        options['body'] = formData;

    // отправить HTTP-запрос
    fetch(url, options)
    .then(response => response.json())
    .then(data => {
        if (data['status'] ==='ok') {
            var previousAction = joinButton.dataset.action;

            // переключить текст кнопки и атрибут data-action
            var action = previousAction === 'join' ? 'unjoin' : 'join';
            joinButton.dataset.action = action;
            joinButton.innerHTML = action;

            // Обновить количество присоединений игроков
            var joinCount = document.querySelector('span.count');
            var totalJoins = parseInt(joinCount.innerHTML.split(' / ')[0]);
            var maxPlayers = parseInt(joinCount.innerHTML.split(' / ')[1]);

            joinCount.innerHTML = previousAction === 'join'
                ? (totalJoins + 1) + ' / ' + maxPlayers
                : (totalJoins - 1) + ' / ' + maxPlayers;

            // Запрашиваем обновленный список игроков
            fetch(`/games/get_player_list/${gameId}/`) // Добавьте это представление для получения списка
                .then(response => response.json())
                .then(playerData => {
                    if (playerData.status === 'ok') {
                        document.querySelector('#player-list').innerHTML = playerData.player_list_html;
                    }
                });
        } else {
            alert(data.message); // Показываем сообщение об ошибке
        }
    })
    .catch(error => {
        console.error("Ошибка: " + error);
    });
});
{% endblock %}

teams/games/templates/games/game/list.html
{% extends "base.html" %}

{% block title %}Games JTeam{% endblock %}

{% block content %}
    <h1>Список доступных игр</h1>
    <p>
        Выбери игру из списка ниже или создай сам <a href="{% url 'games:create' %}"
                                                     class="btn btn-primary">Создать игру</a></p>
        <div id="game-list">
            {% include "games/game/list_games.html" %}
        </div>
{% endblock %}

{% block domready %}
 var page = 1;
  var emptyPage = false;
  var blockRequest = false;

  window.addEventListener('scroll', function(e) {
    var margin = document.body.clientHeight - window.innerHeight - 200;
    if(window.pageYOffset > margin && !emptyPage && !blockRequest) {
      blockRequest = true;
      page += 1;

      fetch('?games_only=1&page=' + page)
      .then(response => response.text())
      .then(html => {
        if (html === '') {
          emptyPage = true;
        }
        else {
          var gameList = document.getElementById('game-list');
          gameList.insertAdjacentHTML('beforeEnd', html);
          blockRequest = false;
        }
      })
    }
  });

  // Launch scroll event
  const scrollEvent = new Event('scroll');
  window.dispatchEvent(scrollEvent);
{% endblock %}

teams/games/templates/games/game/list_games.html
<div class="row row-cols-1 g-2">
{% for game in games %}
    <div class="col">
            <div class="card">
              <div class="card-body">
                <div class="info">
                    <a href="{{ game.get_absolute_url }}">
                        <h3>{{ game.get_sport_display }}&nbsp;&nbsp;&nbsp;</h3>
                        <i class="fas fa-calendar"></i> &nbsp; {{ game.date }}&nbsp;&nbsp;&nbsp;
                        <i class="fas fa-clock"></i> {{ game.start_time }}&nbsp;&nbsp;&nbsp;
                        <i class="fas fa-map-marker"></i> &nbsp; {{ game.place }}
                    </a>
                </div>
              </div>
            </div>
    </div>
{% endfor %}
</div>
<div class="mb-2"></div>
<!--Добавить отображание количества игроков в игре-->

teams/games/templates/games/game/player_list.html
{% for user in joined_players %}
    <div>
        <p>{{ user.username }}</p>
    </div>
{% empty %}
    <div>Nobody players joined</div>
{% endfor %}